language: node_js
node_js:
    - node
script:
  - MONGODB_URI = mongodb+srv://jordantan:Dayonday123@cluster0.5ip1z.mongodb.net/resthub?retryWrites=true&w=majority
  - mocha --exit
services:
  - mongodb
deploy:
  provider: lambda
  function_name: "contactsList"
  region: "us-east-2"
  role: "arn:aws:iam::223172640339:role/service-role/contactsList-role-lwdh7i7t"
  runtime: "nodejs12.x"
  access_key_id: "AKIAJ5X2GT3R4WGYQGAQ"
  secret_access_key: "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"
  handler_name: "handler"
  module_name: "lambda"
  edge: "true"