language: node_js
node_js:
    - node
script:
  - mocha --exit
services:
  - mongodb
deploy:
  provider: lambda
  function_name: "contactsList"
  region: "us-east-2"
  role: "arn:aws:iam::223172640339:role/service-role/contactsList-role-lwdh7i7t"
  runtime: "nodejs12.x"
  access_key_id: "AKIATH5RAHZJZQDM2M4Q"
  secret_access_key: "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"
  handler_name: "handler"
  module_name: "lambda"
  edge: "true"