language: node_js
node_js:
- node
script:
- mocha --exit
services:
- mongodb
deploy:
  provider: lambda
  region: us-east-2
  function_name: contacts
  role: arn:aws:iam::223172640339:role/service-role/contacts-role-e13fus97
  runtime: nodejs12.x
  handler_name: handler
  secret_access_key:
    secure: RBimSm7eO7xwww1IffJTUAJhH+0L9iz6oOski8S6NB6T8RrM03K/v1/ZkPqgssq7DCNX1iwQJBDLF4OcrZvkzvxpI1hBArNU+YQIE0Ul06Angj8BJhEBsUdwbwV7UMnZK7V9JAsO/73hV0GTXcPuZSykh5G69UaHztnOoh3+7Le1YkEnoU5QWBSHtHlh6kVX8eQCko/FTLPBcJ7NahN/cK+i1lMisDl6BXvGl/4xQ1uBJjkwH2k6XEmVwGbiASZpts3mCON0fL+nPydPyZXBVCnaEyqR/A59x/1gYN3WpK4Ov6RSiFd+ENkMWBn91ueHRkQYfsOA97QmAzgZzXrbm7TU/X/wQ/0+UyFnGn2lKAbga1uQ7fN2+PI1rebLYx6z5ByrBqCPot7d7I9bjKhzFUwD2GNlU0fhsmLPKEJA/uDsaii0xrurPT1KjNlHFxZMFyVhBfPR82tPZ4vzLpnpU7cFnAhGXKDbQAnd+DvWEcK8ME8ECGjAVSfS0hOIGT3U3VQspYFba6+of3RIbxI4g8LYbqLgNAveyx8yEw4BwKuWCFpnCa+J5WQ1AHmn0VnGISOQ0y+rqzqnnVAnTMu0X1lEV7NTUnK5xAxbqfsN+ODuLL6ZHapzBj47RQpoylelNbMIiV/ZgbWszMkbyW56OJdtnT7TnyeungHVUhVFIRU=
  access_key_id:
    secure: Va294shfYRo2ORyka/9FpRDcsazFkKne4MlydrYhKlxJaq1RC9UKSAvV7fkUSyqbkK3SK9XIf54+X5YtgimJQVUrFiWWu6Nw3YBL0yEZx7g1ezUIebBXw95bt8PK7KL88MIijRMoFAD2DxikwQOrzZKcC5MZe9yFgSL4qRANKl6WrVePmTXcOxVTAjJkhKvmDbCD83zdLU44KVY/NnxTVPeiJMyXXTU4jZ4CqX9LAYO797fbbHwbETpM4WPINlkyg+VshdnBhaOR3t6SHfjFl4fvyD779NuNDfZk3GhwTZQSy276LjlwThuTpGX2tkAs93O/hhuuwTM02rU2kRcrgrq8p0m0Ejbed7indnndsCbTsdHwjG1ldAKUdRHTTGfQ0PnlENuSBEucpbOM+1HQOKg6X/wjmDhHdwdLr0oyuSiTTJH3FT6ngE2b/tgmIvWhkUdGkd8Hemd+KNoJ0Yo5bXle/xN8Ahov83Wa+him1gCsiX0r5KE8MSpEvvJ43z/g8Es3Hv2YuEy6/diUDvG0+oCQhiZ1jo5CubGHwuf333orI9xLD0UKWQWF0gYQptrcnle2haOsHrleIOTHkOrJ5m+wX1Szna/Uq/MybZHEzBEi4jWTRu52tFVRq7OQgPF0Jdb8e2Jm86NX/glRtFPnsc3o1qRQjxD/1g3ZfPvFnpw=
