service: contacts
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev

  memorySize: 128
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      DB_SOURCE: 'atlas'